{
 "title": "Custom Exporter Monitoring Dashboard",
 "time": { "from": "2025-11-14T03:18:39.218Z", "to": "2025-11-14T15:18:39.218Z" },
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(scrape_duration_seconds,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "List of Targets With Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "scrape_duration_seconds{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg(scrape_duration_seconds)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Collector Duration by Collector",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg(node_scrape_collector_duration_seconds) by (collector)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Min Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "min(scrape_duration_seconds)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scrape Duration by Job",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "avg(scrape_duration_seconds) by (job)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pg_scrape_collector_duration_seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "pg_scrape_collector_duration_seconds{job=\"$job\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "max(scrape_duration_seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "max(scrape_duration_seconds)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Exporter Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "node_scrape_collector_duration_seconds{job=\"$job\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Postgres Exporter Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "pg_exporter_last_scrape_duration_seconds{job=\"$job\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Random Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "random_temperature_celsius\r\n", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Prometheus Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    { "expr": "scrape_duration_seconds\r\n", "legendFormat": "__auto" }
   ]
  }
 ]
}