{
 "title": "Database Monitoring Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "db",
    "query": {
     "query": "label_values(pg_stat_database_xact_commit,datname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Locks count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_locks_count{datname=\"$db\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transaction rollbacks per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_rollback{datname=\"$db\"}[5m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname=\"$db\"} / 1024 / 1024 / 1024\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deadlocks total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "pg_stat_database_deadlocks{datname=\"$db\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "pg_stat_database_blks_hit{datname=\"$db\"} \r\n/ (pg_stat_database_blks_hit{datname=\"$db\"} + pg_stat_database_blks_read{datname=\"$db\"})\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Running Queries",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=\"$db\", state=\"active\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transaction commits per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_rollback{datname=\"$db\"}[5m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=\"$db\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read operations per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_blks_read{datname=\"$db\"}[5m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database size (GB)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname=\"$db\"} / 1024 / 1024 / 1024\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}