{
 "title": "System Monitoring Dashboard",
 "time": { "from": "2025-11-14T10:16:56.662Z", "to": "2025-11-14T10:46:56.662Z" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(node_cpu_seconds_total,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Network Out (bytes/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"$instance\", device!=\"lo\"}[5m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network In (bytes/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"$instance\", device!=\"lo\"}[5m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Write speed (bytes/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total{instance=\"$instance\"}[5m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Read speed (bytes/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{instance=\"$instance\"}[5m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Context Switches per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(node_context_switches_total{instance=\"$instance\"}[5m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM total / used (GB)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$instance\"} / 1024 / 1024 / 1024\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM usage %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=\"$instance\"} \r\n      / node_memory_MemTotal_bytes{instance=\"$instance\"})) * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load average (1 min)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{instance=\"$instance\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage per core %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "100 - (rate(node_cpu_seconds_total{mode=\"idle\", instance=\"$instance\"}[5m]) * 100)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=\"$instance\"}[5m])) * 100)\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}